### ISSUE TITLE
Cypress e2e test failed

### ISSUE THREAD

**Issue by SebsnCGI** [kpmck/nx-workspace-cypress-cucumber#1]
Hi,

I juste cloned your repository and tried to execute e2e tests, but they failed.

I did not modify anything, I launched the project as is from the master branch.

![image](https://user-images.githubusercontent.com/56916459/98375707-c7fb5600-2042-11eb-9691-a96e94e264f6.png)

Is this something that is reproduced on your end?

**Comment by kpmck** [comment]
Hi @SebsnCGI , I apologize - this repo was generated for an issue I wrote up for ReportPortal using Cucumber and Cypress in an Nx monorepo, found here: https://github.com/reportportal/agent-js-cypress/issues/61

So unfortunately, the failure in running the tests is expected until the above referenced ticket is resolved. I should have probably made this repository private, or updated the README file to indicate that it is failing code (which I will do now). Sorry about that!

**Comment by SebsnCGI** [comment]
@kpmck Hello, no worries! I didn't understand that it was just an example project.

I just unlocked the e2e tests on my monorepo nrwl react.

thanks !
